name: Build Windows EXE

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      version:
        description: 'リリースバージョン (例: v1.0.0)'
        required: true
        default: 'v1.0.0'
      release_notes:
        description: 'リリースノート'
        required: false
        default: '新機能と改善点'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    # 依存関係をいれる
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet flet-desktop flet-cli
        
    # pyinstallerのインストール
    - name: install Pyinstaller
      run: |
        git clone https://github.com/pyinstaller/pyinstaller.git
        cd pyinstaller/bootloader
        python ./waf distclean all
        cd ..
        pip install -e .
        
    # exeファイルにする
    - name: Build EXE
      run: |
        flet pack .\VRCOSCWatch.py --name MyApp --onedir --product-name MyApp -y
    
    # zipに圧縮 
    - name: zip
      run: |
        Compress-Archive -Path dist/MyApp/* -DestinationPath dist/MyApp-${{ github.event.inputs.version }}.zip
        
    # アップロード
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: MyApp
        path: dist/MyApp-${{ github.event.inputs.version }}.zip
        
    # リリースの作成
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: MyApp ${{ github.event.inputs.version }}
        body: ${{ github.event.inputs.release_notes }}
        draft: true
        prerelease: false
        files: |
          dist/MyApp-${{ github.event.inputs.version }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
